"""Initial migration

Revision ID: 18362de987c8
Revises: 8ca207cb17fe
Create Date: 2024-09-18 10:46:54.411053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18362de987c8'
down_revision: Union[str, None] = '8ca207cb17fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('timetables_room_id_fkey', 'timetables', type_='foreignkey')
    op.drop_column('timetables', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('timetables_room_id_fkey', 'timetables', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
