"""Init

Revision ID: 326c0956a5c1
Revises: 5e5c043922d9
Create Date: 2024-09-20 13:53:22.295495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '326c0956a5c1'
down_revision: Union[str, None] = '5e5c043922d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('monday', sa.ARRAY(sa.Time()), nullable=False))
    op.add_column('timetables', sa.Column('tuesday', sa.ARRAY(sa.Time()), nullable=False))
    op.add_column('timetables', sa.Column('wednesday', sa.ARRAY(sa.Time()), nullable=False))
    op.add_column('timetables', sa.Column('thursday', sa.ARRAY(sa.Time()), nullable=False))
    op.add_column('timetables', sa.Column('friday', sa.ARRAY(sa.Time()), nullable=False))
    op.drop_column('timetables', 'available_from')
    op.drop_column('timetables', 'available_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('available_to', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('timetables', sa.Column('available_from', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('timetables', 'friday')
    op.drop_column('timetables', 'thursday')
    op.drop_column('timetables', 'wednesday')
    op.drop_column('timetables', 'tuesday')
    op.drop_column('timetables', 'monday')
    # ### end Alembic commands ###
